mov_project/mov_app/urls.py
from django.urls import path

from mov_app import views

app_name = 'mov_app'  # namespace

urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.details, name='details'),
    path('add/', views.add, name='add'),
    path('update/<int:id>/',views.update, name='update'),
    path('delete/<int:id>/',views.delete, name='delete')
]

mov_project/mov_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mov_app.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mov_project/mov_app/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

mov_project/mov_app/forms.py
from django import forms
from .models import movie


class MovieForms(forms.ModelForm):
    class Meta:
        model = movie
        fields = ['name','desc','year','img']

mov_project/mov_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import MovieForms
from .models import movie


# Create your views here.
def index(request):
    mov = movie.objects.all()
    context = {
        'movie_list': mov
    }
    return render(request, "index.html", context)


def details(request, movie_id):
    movi = movie.objects.get(id=movie_id)
    return render(request, 'details.html', {'movie': movi})


def add(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movi = movie(name=name, desc=desc, year=year, img=img)
        movi.save()
    return render(request, 'add.html')


def update(request, id):
    movi = movie.objects.get(id=id)
    form = MovieForms(request.POST or None, request.FILES, instance=movi)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form': form,'movie':movi})


def delete(request,id):
    if request.method =='POST':
        movi=movie.objects.get(id=id)
        movi.delete()
        return redirect('/')
    return render(request,'delete.html')

mov_project/templates/add.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>add movie</title>
</head>
<body>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
  <label for="name">Movie:</label><br>
  <input type="text" id="name" name="name" placeholder="Enter Movie Name"><br>

  <label for="desc">description:</label><br>
  <input type="text" id="desc" name="desc" placeholder="Enter Description"><br>

  <label for="year">Year:</label><br>
  <input type="text" id="year" name="year" placeholder="Enter year"><br><br>

    <input type="file" name="img">

  <input type="submit" value="Submit">
</form>
</body>
</html>
{% endblock %}

mov_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>movies</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

mov_project/templates/delete.html
<form method="post">
    {% csrf_token %}
    Are you want to delete this movie? <br><br>
    <input type="submit">
</form>

mov_project/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
        <img src="{{movie.img.url}}" width="300" height="300">
        </div>
        <div class="col-md-6">
            <h2>{{movie.name}}</h2>
            <h4>{{movie.desc}}</h4>
            <h6>{{movie.year}}</h6>
            <a class="btn btn-warning" href="{% url 'mov_app:update' movie.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'mov_app:delete' movie.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

mov_project/templates/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

mov_project/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 100%; height:100%;" >
              <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="350px" height="350px">
                  <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text" style="padding: 5px;">{{i.desc}}</p>
                    <a href="{% url 'mov_app:details' i.id %}" class="btn btn-warning">View Details</a>
                  </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}